# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-22 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Soil',
        ),
    ]
