# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-22 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_auto_20190622_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soil',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='soil',
            name='afterDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'afterDate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soil',
            name='beforeDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'beforeDate'),
            preserve_default=False,
        ),
    ]
