# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-22 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20190622_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='soil',
            name='price',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soil',
            name='size',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
